[project]
name = "nulattice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12" # only for jax support
dependencies = [
    "numpy>=1.24.4",
    "opt-einsum>=3.4.0",
    "scipy>=1.10.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages=["src/NuLattice"]

[dependency-groups]
dev = [
    "jedi-language-server>=0.42.0",
    "pytest>=8.3.5",
    "pytest-benchmark>=4.0.0",
    "ruff>=0.15.1",
    "numba",
    "matplotlib>=3.7.5",
    "pytest-memray>=1.8.0",
]

torch = [
    "torch>2.0.0",
]

jax = [
    "jax"
]

rocm = [
    "pytorch-triton-rocm",
    "jax[rocm]==0.5.0",
]

cuda = [
    "jax[cuda]"
]

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.3"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-rocm", marker = "sys_platform == 'linux'" }
pytorch-triton-rocm = { index = "pytorch-rocm", marker = "sys_platform == 'linux'" }

